# Generated by Django 3.0.5 on 2020-04-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('january', models.BooleanField()),
                ('february', models.BooleanField()),
                ('march', models.BooleanField()),
                ('april', models.BooleanField()),
                ('may', models.BooleanField()),
                ('june', models.BooleanField()),
                ('july', models.BooleanField()),
                ('august', models.BooleanField()),
                ('september', models.BooleanField()),
                ('october', models.BooleanField()),
                ('november', models.BooleanField()),
                ('december', models.BooleanField()),
            ],
        ),
    ]
