# Generated by Django 3.0.5 on 2020-04-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='creature_type',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
