# Generated by Django 3.0.5 on 2020-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_creature_creature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='seasonality',
            field=models.CharField(default='All year', max_length=256),
            preserve_default=False,
        ),
    ]
